# Generated by Django 4.2.16 on 2024-12-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Project',
            new_name='project',
        ),
    ]
